### PR TITLE
Add support for Keepkey

### PR DESCRIPTION
**Pull request by jmaurice**
This PR adds basic support for KeepKey into Mycelium for Android. The code is actually from 4 months ago, so it might not merge cleanly into your tree anymore.

Demo: https://www.youtube.com/watch?v=e9VGJRKTvHA

I based the KeepKey code off Trezor's code, and I'll leave it to the Mycelium devs how to do inheritance from the base Trezor classes, if you want to go that route at all. As KeepKey's firmware diverges from their fork of Trezor, I'd guess KeepKey will probably keep reverse compatibility...

Also, the strings also need to be localized and few other finishing touches, but for the most part it works fine, and I've tested it extensively over the past few months.

### CODE REVIEW

**Comment by dstanchfield** [comment]
We have independently tested with this with our device and it works great.

**Comment by Giszmo** [comment]
@dstanchfield thank you for your feedback and @jmaurice thank you of course for implementing this. Many users will appreciate this a lot.

DanielW is currently reviewing the change. The change set is 45k LOC but mostly code duplication. I assume it will take a bit to merge this, especially if he goes to the effort of distilling the code duplication into a library.

/me wants a keepkey now :)

**Comment by jmaurice** [comment]
Yeah, I took the shortcut of just duplicating the existing Trezor code so you can easily diff things and decide yourselves how to refactor things within your app. I'm sure @dstanchfield can help you get a KeepKey and in the meantime I'm happy to help test any merge candidates.

**Comment by dstanchfield** [comment]
@Giszmo we would love to send you a KeepKey. If you can provide a good shipping address to darin@keepkey.com, we can get one out to you quickly.  We can also provide them to any other developers that may need one.

**Comment by jmaurice** [comment]
@Giszmo how's it going? would it help you guys if I refactored this into a library ? let me know how I can help :)

**Comment by Giszmo** [comment]
It's going very well. Although @DanielWeigl ended up not using your code, keepkey will be supported shortly. Monday I guess. Beta testers already have it.

**Comment by DanielWeigl** [comment]
Yes, as @Giszmo already said, its now done and just got released. https://www.reddit.com/r/btc/comments/4uvkut/mycelium_adds_support_for_keepkey_ios_wallet_back/

We did not use much of your code, as i refactored the TrezorManager to be more generic and reuse a lot of existing code. 

But as you triggered us to look into it and also but some effort into coding/copying it on your own, I think its fair to offer you a small compensation. 
We created an affiliate link with KeepKey and included it into the app - is it okay for you if we offer you 50% of the affiliate income of the first 3 months? (But ofc I can not promise if we make any sells at all via that link). If so, send us a btc address to developers@mycelium.com.

**Comment by jmaurice** [comment]
Perfect, that was exactly my intention... I don't need compensation tho, just give me a shout out (@wiz) on your thanks page or something ;)

**Comment by dstanchfield** [comment]
Played with it here, it works great!!!  We are spreading the word about this integration, thanks guys!

**Pull request closed without merging**
