### PR TITLE
trezor: set address field in TxOutput only for non-change addresses

### PR DESCRIPTION
**Pull request by prusnak**
This fixes issue with trezor firmware 1.5.0

Fixes https://github.com/mycelium-com/wallet/issues/366

### CODE REVIEW

**Comment by Giszmo** [comment]
Looks plausible to me and it seams to not affect anything but Trezor. I have no trezor to test it but would merge it if no veto comes along within a week.

**Comment by jhoenicke** [comment]
Tested on testnet with old firmware 1.4.2, new firmware 1.5.0, and keepkey old firmware and current firmware.  No problems.

f3823d89d5c3fd0d6e2a5c133195ac254f6cd0a6ff14fb83227377034ffb6264
191512f069d302e08ab090f9d6c920905e7a799b1e98c6c33b5e2ef0f0ad13f4
332ee5d5a4a23058c2751f7499c00004b86bede482c170c024dc2ecfdaf6e5b8

**Comment by Giszmo** [comment]
thanks

**Comment by prusnak** [comment]
When can we expect release of new version including this fix?

**Comment by Giszmo** [comment]
Wednesday? Something like this.

**Pull request merged**
