### PR TITLE
Adjusting proguard to solve error when get pin code in internalization

### PR DESCRIPTION
**Pull request by tairoroberto**
This solve the problem that app stop when user select set pin code in settings menu, when app is in prodnet mode.

### CODE REVIEW

**Comment by DanielWeigl** [comment]
Hello, thank you for you PullRequest, can you explain a bit more how to reproduce the error you try to fix with it? So far we did not experience any crashes while setting the PIN code

**Comment by tairoroberto** [comment]
Hello, i am sorry for not explain the error before, the crash occur when i am in prodnet and i use the language 'pt'. When i make a build the app using the apk signed mode, i can install the in a device normally an it works normally i guess,  i'm not tested all funcionalities, after make a backup is the error moment. When i go to set a new pin code the crash occurs.

The method **Utils.formatBlockcountAsApproxDuration(this.getContext()**, Constants.MIN_PIN_BLOCKHEIGHT_AGE_RESET_PIN)
is called 

and into it has the follow.
**PrettyTime p = new PrettyTime(mbwManager.getLocale());** 
In PrettyTime instantiation that the error occurs

I was make the test in a android 5.1.1 device.

I dont know if i did the right thing, but was the only thing i was found that solved the error without change the code.

**Comment by DanielWeigl** [comment]
Hi, thank you for your response.

Can you try to only include the 

```
+# This is to solve when show error with internalization
 +-keep class org.ocpsoft.prettytime.i18n.**
```

lines? The other one should be unrelated.

If it still crashes, please send us the stack-trace for the crash (copy it from the adb logcat)

**Comment by tairoroberto** [comment]
Hi, 
Yes works only with this line 
**+# This is to solve when show error with internalization
 +-keep class org.ocpsoft.prettytime.i18n.****
Thank you very much for you answer
This was the first time tha a i help a projetct and i am happy for this, and this project is really interesting.

**Comment by DanielWeigl** [comment]
Hi, sorry for bothering you again - but we are unable to reproduce the error on our side.

Can you send us the stacktrace you get, without the changes in `mbw.pro`

**Comment by tairoroberto** [comment]
Hi, no problem 

I commented the line in mbw.pro
And i did this steps.
I make a backup
create a pin code
after make the backup
go to settings
set pin code

I dont clear pin code
I set pin code direct in settings


12-05 11:16:19.435 2355-2393/system_process D/lights: set_light_buttons: 2
12-05 11:16:42.080 4900-4900/com.google.android.googlequicksearchbox:search I/GrammarCompilationSvcCt: #startService for null, APP_NAMES.
12-05 11:16:46.150 2355-2378/system_process I/UsageStatsService: User[0] Flushing usage stats to disk
12-05 11:16:47.180 2355-2486/system_process D/lights: set_light_buttons: 1
12-05 11:17:00.230 2355-2355/system_process D/lights: set_light_buttons: 2
12-05 11:17:04.985 2355-2486/system_process D/lights: set_light_buttons: 1
12-05 11:17:09.990 2355-2393/system_process D/lights: set_light_buttons: 2
12-05 11:17:12.315 2355-2486/system_process D/lights: set_light_buttons: 1
12-05 11:17:24.015 2355-2393/system_process D/lights: set_light_buttons: 2
12-05 11:17:25.335 2355-2511/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
12-05 11:17:25.370 2355-2486/system_process D/lights: set_light_buttons: 1
12-05 11:17:28.375 2355-2511/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
12-05 11:17:37.640 2355-2393/system_process D/lights: set_light_buttons: 2
12-05 11:17:37.760 2355-2486/system_process D/lights: set_light_buttons: 1
12-05 11:17:41.825 2355-3054/system_process I/ActivityManager: START u0 {cmp=com.brq.demowallet/com.brq.wallet.activity.VerifyWordListActivity} from uid 10085 on display 0
12-05 11:17:42.120 2355-2389/system_process I/ActivityManager: Displayed com.brq.demowallet/com.brq.wallet.activity.VerifyWordListActivity: +277ms
12-05 11:17:43.470 2355-2511/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
12-05 11:17:46.495 2355-2511/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
12-05 11:17:50.500 2355-4180/system_process D/DhcpClient: Received packet: b8:88:e3:32:14:0b ACK: your new IP /10.2.69.111, netmask /255.255.248.0, gateways [/10.2.65.200] DNS servers: /10.2.1.206 /10.2.17.202 , lease time 43200
12-05 11:17:50.505 2355-4180/system_process D/DhcpClient: Received packet: b8:88:e3:32:14:0b ACK: your new IP /10.2.69.111, netmask /255.255.248.0, gateways [/10.2.65.200] DNS servers: /10.2.1.206 /10.2.17.202 , lease time 43200
12-05 11:17:50.520 2355-4180/system_process D/DhcpClient: Received packet: b8:88:e3:32:14:0b ACK: your new IP /10.2.69.111, netmask /255.255.248.0, gateways [/10.2.65.200] DNS servers: /10.2.1.206 /10.2.17.202 , lease time 43200
12-05 11:18:00.120 2355-2379/system_process I/ProcessStatsService: Prepared write state in 12ms
12-05 11:18:46.885 2355-2511/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
12-05 11:18:49.935 2355-2511/system_process D/ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
12-05 11:18:51.985 2355-2365/system_process I/art: Background sticky concurrent mark sweep GC freed 83430(7MB) AllocSpace objects, 25(680KB) LOS objects, 31% free, 18MB/27MB, paused 10.757ms total 248.922ms
12-05 11:18:57.140 2355-3054/system_process W/InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@bca47ed (uid=10085 pid=8247)
12-05 11:18:57.425 8247-8321/com.brq.demowallet I/Wapi: Connecting to https://node3.mycelium.com/wapitestnet (0)
12-05 11:18:57.430 8247-8322/com.brq.demowallet I/Wapi: Connecting to https://node3.mycelium.com/wapitestnet (0)
12-05 11:18:57.435 8247-8323/com.brq.demowallet I/Wapi: Starting sync: SyncMode{NORMAL_SYNC, onlyActiveAccount}
12-05 11:18:57.480 8247-8323/com.brq.demowallet I/Wapi: Connecting to https://node3.mycelium.com/wapitestnet (0)
12-05 11:18:58.450 8247-8321/com.brq.demowallet I/Wapi: Wapi getVersionEx finished (1022ms)
12-05 11:18:58.455 8247-8322/com.brq.demowallet I/Wapi: Wapi queryExchangeRates finished (1026ms)
12-05 11:18:58.460 8247-8323/com.brq.demowallet I/Wapi: Wapi queryUnspentOutputs finished (979ms)
12-05 11:19:03.360 8247-8247/com.brq.demowallet I/ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
12-05 11:19:03.390 8247-8247/com.brq.demowallet W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
12-05 11:19:05.330 2355-6222/system_process I/ActivityManager: START u0 {cmp=com.brq.demowallet/com.brq.wallet.activity.settings.SettingsActivity} from uid 10085 on display 0
12-05 11:19:05.535 2355-2980/system_process W/ActivityManager: Unable to start service Intent { act=com.ledger.wallet.service.ILedgerWalletService pkg=com.ledger.wallet.service } U=0: not found
12-05 11:19:05.545 2355-3951/system_process W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@48897f6
12-05 11:19:05.740 8247-8271/com.brq.demowallet D/OpenGLRenderer: endAllStagingAnimators on 0x58d6dec0 (MenuPopupWindow$MenuDropDownListView) with handle 0x5804ab28
12-05 11:19:05.815 2355-2389/system_process I/ActivityManager: Displayed com.brq.demowallet/com.brq.wallet.activity.settings.SettingsActivity: +435ms
12-05 11:19:10.505 8247-8247/com.brq.demowallet D/AndroidRuntime: Shutting down VM
12-05 11:19:10.535 8247-8247/com.brq.demowallet E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.brq.demowallet, PID: 8247
                                                                  Theme: themes:{}
                                                                  java.util.MissingResourceException: Can't find resource for bundle 'org.ocpsoft.prettytime.i18n.Resources_pt', key ''
                                                                      at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
                                                                      at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
                                                                      at java.util.ResourceBundle.getBundle(ResourceBundle.java:159)
                                                                      at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(ResourcesTimeFormat.java:30)
                                                                      at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(ResourcesTimeFormat.java:16)
                                                                      at org.ocpsoft.prettytime.PrettyTime.addUnit(PrettyTime.java:1468)
                                                                      at org.ocpsoft.prettytime.PrettyTime.initTimeUnits(PrettyTime.java:127)
                                                                      at org.ocpsoft.prettytime.PrettyTime.<init>(PrettyTime.java:94)
                                                                      at com.brq.wallet.Utils.formatBlockcountAsApproxDuration(Utils.java:239)
                                                                      at com.brq.wallet.NewPinDialog.updateResetInfo(NewPinDialog.java:73)
                                                                      at com.brq.wallet.NewPinDialog.<init>(NewPinDialog.java:65)
                                                                      at com.brq.wallet.MbwManager.showSetPinDialog(MbwManager.java:688)
                                                                      at com.brq.wallet.activity.settings.SettingsActivity$2.onPreferenceClick(SettingsActivity.java:104)
                                                                      at android.preference.Preference.performClick(Preference.java:996)
                                                                      at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                                      at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                      at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                      at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-05 11:19:10.535 2355-2649/system_process W/ActivityManager:   Force finishing activity com.brq.demowallet/com.brq.wallet.activity.settings.SettingsActivity
12-05 11:19:10.570 8247-8332/com.brq.demowallet I/Wapi: Connecting to https://node3.mycelium.com/wapitestnet (0)
12-05 11:19:10.605 8247-8258/com.brq.demowallet I/art: Background sticky concurrent mark sweep GC freed 63857(3MB) AllocSpace objects, 15(300KB) LOS objects, 18% free, 14MB/17MB, paused 1.382ms total 179.535ms
12-05 11:19:10.660 2355-2492/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
12-05 11:19:11.050 2355-2379/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{a8a051b u0 com.brq.demowallet/com.brq.wallet.activity.settings.SettingsActivity t26 f}
12-05 11:19:11.690 8247-8332/com.brq.demowallet I/Wapi: Wapi collectError finished (1123ms)
12-05 11:19:11.810 8247-8332/com.brq.demowallet E/MyceliumWallet: uncaught exception
                                                                  java.util.MissingResourceException: Can't find resource for bundle 'org.ocpsoft.prettytime.i18n.Resources_pt', key ''
                                                                      at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
                                                                      at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
                                                                      at java.util.ResourceBundle.getBundle(ResourceBundle.java:159)
                                                                      at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(ResourcesTimeFormat.java:30)
                                                                      at org.ocpsoft.prettytime.impl.ResourcesTimeFormat.setLocale(ResourcesTimeFormat.java:16)
                                                                      at org.ocpsoft.prettytime.PrettyTime.addUnit(PrettyTime.java:1468)
                                                                      at org.ocpsoft.prettytime.PrettyTime.initTimeUnits(PrettyTime.java:127)
                                                                      at org.ocpsoft.prettytime.PrettyTime.<init>(PrettyTime.java:94)
                                                                      at com.brq.wallet.Utils.formatBlockcountAsApproxDuration(Utils.java:239)
                                                                      at com.brq.wallet.NewPinDialog.updateResetInfo(NewPinDialog.java:73)
                                                                      at com.brq.wallet.NewPinDialog.<init>(NewPinDialog.java:65)
                                                                      at com.brq.wallet.MbwManager.showSetPinDialog(MbwManager.java:688)
                                                                      at com.brq.wallet.activity.settings.SettingsActivity$2.onPreferenceClick(SettingsActivity.java:104)
                                                                      at android.preference.Preference.performClick(Preference.java:996)
                                                                      at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
                                                                      at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                      at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                      at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-05 11:19:15.555 2355-2393/system_process D/lights: set_light_buttons: 2
12-05 11:19:18.755 2994-4557/com.android.vending I/PlayCommon: [102] com.google.android.play.a.g.e(853): Preparing logs for uploading
12-05 11:19:18.760 2994-4557/com.android.vending I/PlayCommon: [102] com.google.android.play.a.g.e(855): No file ready to send
12-05 11:19:20.550 2355-2379/system_process W/ActivityManager: Launch timeout has expired, giving up wake lock!
12-05 11:19:48.130 5187-8343/.esfm W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar

**Comment by DanielWeigl** [comment]
Okay, thank you very much. Please update the pull request to only include the one line regarding i18n, then ill merge it

**Comment by tairoroberto** [comment]
OK

**Pull request merged**
